name: First GitHub Action

on:
  push:
    branches:
      - main 

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello fsfsdf sfsdf sfs from GitHub Actions dsfsdfs"
